__version__ = "1.0.0"
__author__ = "Nifogi"

from .constants import MAZE_SCALE, MAX_MAZE_SIZE, ANIMATION_SPEED, MAZE_BORDER_WIDTH_PERCENT, DEFAULT_CELL_SIZE, WINDOW_MARGIN, ROTATION_SPEED, GRAVITY, PLAYER_SIZE, PLAYER_BORDER, MAZE_BORDER_COLOR, MAZE_BACKGROUND_COLOR, PLAYER_COLOR, BLACK, GREEN, RED

__all__ = [
    "__version__",
    "__author__",
    'MAZE_SCALE',
    'ANIMATION_SPEED',
    'MAX_MAZE_SIZE',
    'MAZE_BORDER_WIDTH_PERCENT',
    'DEFAULT_CELL_SIZE',
    'WINDOW_MARGIN',
    'ROTATION_SPEED',
    'GRAVITY',
    'PLAYER_SIZE',
    'PLAYER_BORDER',
    'MAZE_BORDER_COLOR',
    'MAZE_BACKGROUND_COLOR',
    'PLAYER_COLOR',
    'BLACK',
    'GREEN',
    'RED',
]
