__version__ = "1.0.0"
__author__ = "Nifogi"

from .constants import MAZE_SCALE, ANIMATION_SPEED
from .constants import MAZE_BORDER_WIDTH_PERCENT, DEFAULT_CELL_SIZE
from .constants import WINDOW_MARGIN, ROTATION_SPEED, GRAVITY, PLAYER_BOUNCE
from .constants import AIR_DRAG, FRICTION, PLAYER_SIZE, PLAYER_BORDER
from .constants import MAZE_BORDER_COLOR, MAZE_BACKGROUND_COLOR, PLAYER_COLOR
from .constants import PLAYER_BORDER_COLOR, BLACK, WHITE, GREEN, RED, TURQUOISE
from .constants import MAZE_SOLUTION_COLOR, ORANGE, LOGO_COLOR
from .constants import MAZE_PLAYER_SOLUTION_COLOR, PURPLE

__all__ = [
    "__version__",
    "__author__",
    'MAZE_SCALE',
    'ANIMATION_SPEED',
    'MAZE_BORDER_WIDTH_PERCENT',
    'DEFAULT_CELL_SIZE',
    'WINDOW_MARGIN',
    'ROTATION_SPEED',
    'GRAVITY',
    'PLAYER_BOUNCE',
    'AIR_DRAG',
    'FRICTION',
    'PLAYER_SIZE',
    'PLAYER_BORDER',
    'MAZE_BORDER_COLOR',
    'MAZE_BACKGROUND_COLOR',
    'MAZE_SOLUTION_COLOR',
    'MAZE_PLAYER_SOLUTION_COLOR',
    'LOGO_COLOR',
    'PLAYER_COLOR',
    'PLAYER_BORDER_COLOR',
    'BLACK',
    'WHITE',
    'GREEN',
    'RED',
    'TURQUOISE',
    'ORANGE',
    'PURPLE',
]
