# OVERALL
MAZE_SCALE = 0.95

# MAZE
MAZE_BORDER_WIDTH_PERCENT = 10
DEFAULT_CELL_SIZE = 75
WINDOW_MARGIN = 200

# GAME
ROTATION_SPEED = 100
GRAVITY = 5

# COLORS
LIGHT_NAVY = 0xFF_80_FF_FF
DARK_NAVY = 0xFF_00_00_40

LIGHT_PINK = 0x_FF_FF_69_B4


MAZE_BORDER_COLOR = LIGHT_NAVY
MAZE_BACKGROUND_COLOR = DARK_NAVY

PLAYER_COLOR = LIGHT_PINK
